### ISSUE TITLE
File not saving after editing in nvim

### ISSUE THREAD

**Issue by dmytrodubinin** [ZwodahS/jopvim.nvim#1]
When I try to save file after editing in nvim I get this error;

```
Error detected while processing BufWritePost Autocommands for "*.jop.md":
E5108: Error executing lua ...ocal/share/nvimvimplug/plenary.nvim/lua/plenary/path.lu
a:317: Path not valid
stack traceback:
        [C]: in function 'error'
        ...ocal/share/nvimvimplug/plenary.nvim/lua/plenary/path.lua:317: in function
'expand'
        ...ocal/share/nvimvimplug/plenary.nvim/lua/plenary/path.lua:685: in function
'is_file'
        ...ocal/share/nvimvimplug/plenary.nvim/lua/plenary/curl.lua:188: in function
'request'
        ...ocal/share/nvimvimplug/plenary.nvim/lua/plenary/curl.lua:240: in function
'put'
        .../.local/share/nvimvimplug/jopvim.nvim/lua/jopvim/api.lua:36: in function '
put'
        .../.local/share/nvimvimplug/jopvim.nvim/lua/jopvim/api.lua:63: in function '
update_note'
        ....local/share/nvimvimplug/jopvim.nvim/lua/jopvim/init.lua:56: in function '
on_bufWritePost'
        [string ":lua"]:1: in main chunk
```
![image](https://user-images.githubusercontent.com/8066458/167191160-7029426e-d799-41fd-8b23-2f5fab01e486.png)

OS: Fedora 35
Joplin 2.7.15 (prod, linux)
Neovim 0.8

**Comment by ZwodahS** [comment]
@dmytrodubinin hmmm do you have the commit hash for plenary that you are using ?
if you are in the joplin discord, feel free to ping me there.

**Comment by ZwodahS** [comment]
I found the problem. somehow if your notes contains a "$", plenary has this weird bug that couldn't send the data across. I will try to fix this on plenary side later on.

If you need this to work, you can take my patch for the plenary at https://github.com/ZwodahS/plenary.nvim/tree/fix/path

**Comment by dmytrodubinin** [comment]
Thanks!

**Comment by ZwodahS** [comment]
Fixed this in another commit(jopvim) that use raw_body instead of body to avoid the is_file call of plenary so that the fix for plenary is no longer necessary.

Will close the issue for now
